---
- hosts: ghost
  tasks:

  ##############################
  # Common
  ##############################

  - name: Common | Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - nginx
      - nodejs
      - unzip
      - upstart
